### ISSUE TITLE
Cannot find module './emojis.json' when building

### ISSUE THREAD

**Issue by negimaru** [ealush/emoji-picker-react#294]
I am using vite for my chat App but when it tries to build  it gives me the following error.
Cannot find module './emojis.json' or its corresponding type declarations.

It seems that the file is missing or is not finding it, but after a few days I could not find a solution.

![image](https://user-images.githubusercontent.com/14748038/201075963-a0521811-84c9-43b4-a998-0cca677676f2.png)

**Comment by ealush** [comment]
I cannot reproduce this on my end. Do you have a repo that I can try?

**Comment by negimaru** [comment]
Sadly not yet, but i will make one and try to reproduce the error, no problem

I will aswer again to this issue when the repo is done!

Thanks!

I also leave you a tree of the directory in case there is a missing file.
├── dist
│   ├── components
│   │   ├── atoms
│   │   │   └── Button.d.ts
│   │   ├── body
│   │   │   ├── Body.d.ts
│   │   │   ├── EmojiCategory.d.ts
│   │   │   ├── EmojiList.d.ts
│   │   │   ├── EmojiVariationPicker.d.ts
│   │   │   └── Suggested.d.ts
│   │   ├── context
│   │   │   ├── ElementRefContext.d.ts
│   │   │   ├── PickerConfigContext.d.ts
│   │   │   └── PickerContext.d.ts
│   │   ├── emoji
│   │   │   ├── Emoji.d.ts
│   │   │   └── ExportedEmoji.d.ts
│   │   ├── ErrorBoundary.d.ts
│   │   ├── footer
│   │   │   └── Preview.d.ts
│   │   ├── header
│   │   │   ├── Header.d.ts
│   │   │   ├── Search.d.ts
│   │   │   └── SkinTonePicker.d.ts
│   │   ├── Layout
│   │   │   ├── Absolute.d.ts
│   │   │   ├── Flex.d.ts
│   │   │   ├── Relative.d.ts
│   │   │   └── Space.d.ts
│   │   ├── main
│   │   │   └── PickerMain.d.ts
│   │   └── navigation
│   │       └── CategoryNavigation.d.ts
│   ├── config
│   │   ├── categoryConfig.d.ts
│   │   ├── cdnUrls.d.ts
│   │   ├── config.d.ts
│   │   └── useConfig.d.ts
│   ├── data
│   │   ├── emojis.d.ts
│   │   ├── groups.d.ts
│   │   └── skinToneVariations.d.ts
│   ├── dataUtils
│   │   ├── alphaNumericEmojiIndex.d.ts
│   │   ├── asEmoji.d.ts
│   │   ├── DataTypes.d.ts
│   │   ├── emojiSelectors.d.ts
│   │   ├── parseNativeEmoji.d.ts
│   │   └── suggested.d.ts
│   ├── DomUtils
│   │   ├── categoryNameFromDom.d.ts
│   │   ├── classNames.d.ts
│   │   ├── elementPositionInRow.d.ts
│   │   ├── focusElement.d.ts
│   │   ├── getActiveElement.d.ts
│   │   ├── isDarkTheme.d.ts
│   │   ├── keyboardNavigation.d.ts
│   │   ├── scrollTo.d.ts
│   │   └── selectors.d.ts
│   ├── emoji-picker-react.cjs.development.css
│   ├── emoji-picker-react.cjs.development.js
│   ├── emoji-picker-react.cjs.development.js.map
│   ├── emoji-picker-react.cjs.production.min.js
│   ├── emoji-picker-react.cjs.production.min.js.map
│   ├── EmojiPickerReact.d.ts
│   ├── emoji-picker-react.esm.js
│   ├── emoji-picker-react.esm.js.map
│   ├── hooks
│   │   ├── preloadEmoji.d.ts
│   │   ├── useActiveCategoryScrollDetection.d.ts
│   │   ├── useCloseAllOpenToggles.d.ts
│   │   ├── useDebouncedState.d.ts
│   │   ├── useDisallowedEmojis.d.ts
│   │   ├── useDisallowMouseMove.d.ts
│   │   ├── useEmojiPreviewEvents.d.ts
│   │   ├── useFilter.d.ts
│   │   ├── useFocus.d.ts
│   │   ├── useInitialLoad.d.ts
│   │   ├── useIsEmojiHidden.d.ts
│   │   ├── useIsSearchMode.d.ts
│   │   ├── useKeyboardNavigation.d.ts
│   │   ├── useMouseDownHandlers.d.ts
│   │   ├── useOnFocus.d.ts
│   │   ├── useOnScroll.d.ts
│   │   ├── useScrollCategoryIntoView.d.ts
│   │   ├── useSetVariationPicker.d.ts
│   │   └── useShouldShowSkinTonePicker.d.ts
│   ├── index.d.ts
│   ├── index.js
│   └── types
│       └── exposedTypes.d.ts
├── LICENSE
├── package.json
├── README.md
└── src
    ├── components
    │   ├── atoms
    │   │   └── Button.tsx
    │   ├── body
    │   │   ├── Body.css
    │   │   ├── Body.tsx
    │   │   ├── EmojiCategory.css
    │   │   ├── EmojiCategory.tsx
    │   │   ├── EmojiList.css
    │   │   ├── EmojiList.tsx
    │   │   ├── EmojiVariationPicker.css
    │   │   ├── EmojiVariationPicker.tsx
    │   │   ├── Suggested.tsx
    │   │   └── svg
    │   │       └── triangle.svg
    │   ├── context
    │   │   ├── ElementRefContext.tsx
    │   │   ├── PickerConfigContext.tsx
    │   │   └── PickerContext.tsx
    │   ├── emoji
    │   │   ├── Emoji.css
    │   │   ├── Emoji.tsx
    │   │   └── ExportedEmoji.tsx
    │   ├── ErrorBoundary.tsx
    │   ├── footer
    │   │   ├── Preview.css
    │   │   └── Preview.tsx
    │   ├── header
    │   │   ├── Header.css
    │   │   ├── Header.tsx
    │   │   ├── Search.css
    │   │   ├── Search.tsx
    │   │   ├── SkinTonePicker.css
    │   │   ├── SkinTonePicker.tsx
    │   │   └── svg
    │   │       ├── magnifier.svg
    │   │       └── times.svg
    │   ├── Layout
    │   │   ├── Absolute.tsx
    │   │   ├── Flex.css
    │   │   ├── Flex.tsx
    │   │   ├── Relative.tsx
    │   │   └── Space.tsx
    │   ├── main
    │   │   ├── PickerMain.css
    │   │   └── PickerMain.tsx
    │   └── navigation
    │       ├── CategoryNavigation.css
    │       ├── CategoryNavigation.tsx
    │       └── svg
    │           └── CategoryNav.svg
    ├── config
    │   ├── categoryConfig.ts
    │   ├── cdnUrls.ts
    │   ├── config.ts
    │   └── useConfig.ts
    ├── data
    │   ├── emojis.json
    │   ├── emojis.ts
    │   ├── groups.ts
    │   └── skinToneVariations.ts
    ├── dataUtils
    │   ├── alphaNumericEmojiIndex.ts
    │   ├── asEmoji.ts
    │   ├── DataTypes.ts
    │   ├── emojiSelectors.ts
    │   ├── parseNativeEmoji.ts
    │   └── suggested.ts
    ├── DomUtils
    │   ├── categoryNameFromDom.ts
    │   ├── classNames.ts
    │   ├── elementPositionInRow.ts
    │   ├── focusElement.ts
    │   ├── getActiveElement.ts
    │   ├── isDarkTheme.ts
    │   ├── keyboardNavigation.ts
    │   ├── scrollTo.ts
    │   └── selectors.ts
    ├── EmojiPickerReact.css
    ├── EmojiPickerReact.tsx
    ├── hooks
    │   ├── preloadEmoji.ts
    │   ├── useActiveCategoryScrollDetection.ts
    │   ├── useCloseAllOpenToggles.ts
    │   ├── useDebouncedState.ts
    │   ├── useDisallowedEmojis.ts
    │   ├── useDisallowMouseMove.ts
    │   ├── useEmojiPreviewEvents.ts
    │   ├── useFilter.ts
    │   ├── useFocus.ts
    │   ├── useInitialLoad.ts
    │   ├── useIsEmojiHidden.ts
    │   ├── useIsSearchMode.ts
    │   ├── useKeyboardNavigation.ts
    │   ├── useMouseDownHandlers.ts
    │   ├── useOnFocus.ts
    │   ├── useOnScroll.ts
    │   ├── useScrollCategoryIntoView.ts
    │   ├── useSetVariationPicker.ts
    │   └── useShouldShowSkinTonePicker.ts
    ├── index.tsx
    └── types
        └── exposedTypes.ts

**Comment by MertHaddad** [comment]
react-create-app did not cause this problem, but after I converted to Vite this issue showed.

Any idea how to fix it?

**Comment by MertHaddad** [comment]
@negimaru I guess I found the fix!
after I added **"emojis.json"** to _node_modules/emoji-picker-react/**dist**/data/_
I was able to build my app successfully.
@ealush can you do this fix soon since I am not able to build on the cloud since the main module is still not working.
Thanks for the package btw awesome!

**Comment by MertHaddad** [comment]
@negimaru or simply set : "skipLibCheck": true, in tsconfig.json.

**Comment by ivan8v** [comment]
Same issue here, trying to build with `tsc && vite build` on v4.4.9
typescript 5.1.3
```
node_modules/emoji-picker-react/dist/data/emojis.d.ts:1:20 - error TS2307: Cannot find module './emojis.json' or its corresponding type declarations.
```

**Comment by ivan8v** [comment]
It works fine on `3.6.5` by the way, it seems like `^4.0.0` versions are using a different build method that's preventing the JSON file from reaching the `dist` folder

**Comment by ealush** [comment]
@ivan8v 
I just published `emoji-picker-react@4.4.10-rc.1` with a possible fix. Can you please let me know if it works on your end?

**Comment by ivan8v** [comment]
> @ivan8v I just published `emoji-picker-react@4.4.10-rc.1` with a possible fix. Can you please let me know if it works on your end? If it does, I'll publish to main.

It builds perfectly now, thank you very much for the quick response!!

**Comment by ealush** [comment]
Ok then, published 4.4.10. Should be ok now. Thanks for the feedback!
